"""Add reported_by_email to Complaint model

Revision ID: 24b16aef2a60
Revises: c67a2d193a4c
Create Date: 2025-06-06 16:09:49.176317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b16aef2a60'
down_revision = 'c67a2d193a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_by_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('reported_by_email')

    # ### end Alembic commands ###
