"""Initial migration; create user and complaint tables

Revision ID: 3569b05ee918
Revises: 
Create Date: 2025-06-06 13:11:12.834535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3569b05ee918'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(length=20), nullable=False),
    sa.Column('issue_type', sa.Enum('POTHOLE', 'STREETLIGHT_OUTAGE', 'BROKEN_SIDEWALK', 'TRASH_OVERFLOW', 'GRAFFITI', 'OTHER', name='issuetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address_text', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('reported_by_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='complaintstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaints')
    op.drop_table('users')
    # ### end Alembic commands ###
