"""Remove complaint assignment and simplify user roles

Revision ID: b248c17a4c10
Revises: 24b16aef2a60
Create Date: 2025-06-07 13:36:03.937269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b248c17a4c10'
down_revision = '24b16aef2a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('complaints_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('assigned_to_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('complaints_ibfk_1'), 'users', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###
