"""Add citizen user registration and complaint relationship

Revision ID: e8c7bd41017c
Revises: b248c17a4c10
Create Date: 2025-06-07 18:55:19.235350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8c7bd41017c'
down_revision = 'b248c17a4c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reporter_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['assigned_to_id'], ['id'])
        batch_op.drop_column('reported_by_name')
        batch_op.drop_column('reported_by_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_by_email', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('reported_by_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('reporter_id')

    # ### end Alembic commands ###
